### ISSUE TITLE
Blank page when run on linux

### ISSUE THREAD

**Issue by Stesus** [n-patel/southwest-scraper#1]
I've run this on Windows and Linux, and it works fine on Windows. When I try it on Linux, the browser returns only '<html><head></head><body></body></html>'. Do you know what could be wrong?

**Comment by Stesus** [comment]
It turns out it was an SSL error. I changed the code in app to 

`browser = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true', '--ssl-protocol=any'])`

**Comment by n-patel** [comment]
Thanks for posting your solution!
